# Generated by Django 3.0.3 on 2020-10-14 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Main courses', 'Main courses'), ('Steaks', 'Steaks'), ('Desserts', 'Desserts'), ('Drinks and Beverage', 'Drinks and Beverage')], max_length=30)),
                ('image', models.ImageField(default='default.jpg', upload_to='item_pics')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('available', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(default=1)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Vendor')),
            ],
        ),
    ]
